var exports = module.exports;

exports.property = [
    {key: 'CAct', val: 'Catalytic Activity'},
    {key: 'CCnc', val: 'Catalytic Concentration'},
    {key: 'CRto', val: 'Catalytic Ratio'},
    {key: 'CCnt', val: 'Catalytic Content'},
    {key: 'CFr.DF', val: 'Decimal catalytic fraction'},
    {key: 'CFr', val: 'Catalytic Fraction'},
    {key: 'CRat', val: 'Catalytic Rate'},
    {key: 'RelCCnc', val: 'Relative Catalytic Concentration'},
    {key: 'CSub', val: 'Catalytic Substance'},
    {key: 'EntCat', val: 'Entitic Catalytic Activity'},
    {key: 'EntLen', val: 'Entitic Length'},
    {key: 'EntLogNum', val: 'Logarithmic entitic number'},
    {key: 'EntMass', val: 'Entitic Mass'},
    {key: 'EntNum', val: 'Entitic Number'},
    {key: 'EntVol', val: 'Entitic Volume'},
    {key: 'EntSub', val: 'Entitic Substance'},
    {key: 'EntSRto', val: 'Entitic Substance Ratio'},
    {key: 'ArMass', val: 'Mass/Area'},
    {key: 'MCnc', val: 'Mass Concentration'},
    {key: 'MCncSq', val: 'Mass Concentration Squared'},
    {key: 'MCnt', val: 'Mass Content'},
    {key: 'MDiff', val: 'Mass difference'},
    {key: 'MFr.DF', val: 'Mass Decimal Fraction'},
    {key: 'MFrDiff', val: 'Mass Fraction Difference'},
    {key: 'MFr', val: 'Mass Fraction'},
    {key: 'MRat', val: 'Mass Rate'},
    {key: 'MRto', val: 'Mass Ratio'},
    {key: 'RelMCnc', val: 'Relative Mass Concentration'},
    {key: 'RelMRat', val: 'Relative Mass Rate'},
    {key: 'ThrMCnc', val: 'Threshold Mass Concentration'},
    {key: 'MCncDiff', val: 'Difference in Mass Concentration'},
    {key: 'MCPctDiff', val: 'Percent Difference in Mass Concentration'},
    {key: 'RelSCnc', val: 'Relative Substance Concentration'},
    {key: 'Sub', val: 'Substance Amount'},
    {key: 'SCncSq', val: 'Substance Concentration Squared'},
    {key: 'SCnc', val: 'Substance Concentration'},
    {key: 'SRto', val: 'Substance Ratio'},
    {key: 'SCnt', val: 'Substance Content'},
    {key: 'SFr', val: 'Substance Fraction'},
    {key: 'SFr.DF', val: 'Decimal Substance Fraction'},
    {key: 'SRat', val: 'Substance Rate'},
    {key: 'RelSRat', val: 'Relative Substance Rate'},
    {key: 'ThrSCnc', val: 'Threshold Substance Concentration'},
    {key: 'SCncDiff', val: 'Difference in Substance Concentration'},
    {key: 'LsCnc', val: 'Log substance concentration'},
    {key: 'Num', val: 'Number'},
    {key: 'Naric', val: 'Number Aeric (number per area)'},
    {key: 'NCnc', val: 'Number Concentration (count/vol)'},
    {key: 'NCnt', val: 'Number Content = Count/Mass'},
    {key: 'NFr', val: 'Number Fraction'},
    {key: 'NRat', val: 'Number=Count/Time'},
    {key: 'NRto', val: 'Number Ratio'},
    {key: 'LnRto', val: 'Log Number Ratio'},
    {key: 'LnCnc', val: 'Log Number Concentration'},
    {key: 'Vol', val: 'Volume'},
    {key: 'VCnt', val: 'Volume Content'},
    {key: 'VFr.DF', val: 'Volume Decimal Fraction'},
    {key: 'VFr', val: 'Volume Fraction'},
    {key: 'VRat', val: 'Volume Rate'},
    {key: 'VRatCnt', val: 'Volume Rate Content'},
    {key: 'VRatRto', val: 'Volume Rate Ratio'},
    {key: 'VRto', val: 'Volume Ratio'},
    {key: 'RelVol', val: 'Relative Volume'},
    {key: 'RelVRat', val: 'Relative Volume Rate'},
    {key: 'ArVol', val: 'Volume/Area'},
    {key: 'ArVRat', val: 'Volume Rate/Area'},
    {key: 'VFrDiff', val: 'Difference in Volume Fraction'},
    {key: 'VPctDiff', val: 'Percent Volume Difference'},
    {key: 'VRtoPctDiff', val: 'Percent Volume Ratio Difference'},
    {key: 'Time', val: 'Time duration'},
    {key: 'TRto', val: 'Time Ratio'},
    {key: 'TQ2', val: 'Timing Quantity 2'},
    {key: 'RelTime', val: 'Relative Time'},
    {key: 'DateRange', val: 'Date Range'},
    {key: 'ClockTime', val: 'Clock Time'},
    {key: 'TmStp', val: 'Time Stamp—Date and Time'},
    {key: 'TimeDif', val: 'Difference in time duration'},
    {key: 'TimeFr', val: 'Time Fraction'},
    {key: 'ACnc', val: 'Arbitrary Concentration'},
    {key: 'ACnt', val: 'Arbitrary Content'},
    {key: 'ThrACnc', val: 'Threshold Arbitrary Concentration'},
    {key: 'ARat', val: 'Arbitrary Rate'},
    {key: 'LaCnc', val: 'Log Arbitrary Concentration'},
    {key: 'RelACnc', val: 'Relative Arbitrary Concentration'},
    {key: 'AFr', val: 'Arbitrary Fraction'},
    {key: 'Accel', val: 'Acceleration'},
    {key: 'Addr', val: 'Address'},
    {key: 'Anat', val: 'Anatomy'},
    {key: 'Angle', val: 'Angle'},
    {key: 'Aper', val: 'Appearance'},
    {key: 'Arb', val: 'Arbitrary'},
    {key: 'ArArea', val: 'Area/Area'},
    {key: 'AreaFr', val: 'Area Fraction'},
    {key: 'AreaRto', val: 'Area Ratio'},
    {key: 'Bib', val: 'Bibliographic Citation'},
    {key: 'Circ', val: 'Circumference'},
    {key: 'CircFr', val: 'Circumference Fraction'},
    {key: 'Class', val: 'Class'},
    {key: 'ColorRto', val: 'Color Ratio'},
    {key: 'Compli', val: 'Compliance'},
    {key: 'CompliRto', val: 'Compliance Ratio'},
    {key: 'Cmplx', val: 'Complex'},
    {key: 'Desc', val: 'Description'},
    {key: 'Diam', val: 'Diameter'},
    {key: 'Dosage', val: 'Dosage'},
    {key: 'ElpotRat', val: 'Voltage Rate (=Amperage)'},
    {key: 'ElpotRto', val: 'Electrical Potential Ratio'},
    {key: 'Elpot', val: 'Electrical Potential (Voltage)'},
    {key: 'EmailAddr', val: 'E-mail Address'},
    {key: 'ArEnrg', val: 'Energy/Area'},
    {key: 'EngCnc', val: 'Energy Concentration'},
    {key: 'EngCnt', val: 'Energy Content'},
    {key: 'EngFr', val: 'Energy Fraction'},
    {key: 'EngRatFr', val: 'Energy Ratio Fraction'},
    {key: 'EngRat', val: 'Power = Energy/Time'},
    {key: 'EngRto', val: 'Energy Ratio'},
    {key: 'Enrg', val: 'Energy'},
    {key: 'Equ', val: 'Equation'},
    {key: 'Fcn', val: 'Function'},
    {key: 'Find', val: 'Finding'},
    {key: 'FldConduct', val: 'Fluid Conductance'},
    {key: 'FldResist', val: 'Fluid Resistance'},
    {key: 'Force', val: 'Mechanical Force'},
    {key: 'Freq', val: 'Frequency'},
    {key: 'Hx', val: 'History'},
    {key: 'Imp', val: 'Impression/interpretation of study'},
    {key: 'Instrct', val: 'Instructions'},
    {key: 'InvLen', val: 'Inverse Length'},
    {key: 'Inverse VI', val: 'Inverse Inspired Volume'},
    {key: 'LenFr', val: 'Length Fraction'},
    {key: 'LenRto', val: 'Length Ratio'},
    {key: 'LogLenRto', val: 'Log Length Ratio'},
    {key: 'Len', val: 'Length'},
    {key: 'ArLen', val: 'Length/Area'},
    {key: 'Likelihood', val: 'Likelihood'},
    {key: 'Loc', val: 'Location'},
    {key: 'LogInvPct', val: 'Log Inverse Percent'},
    {key: 'LogRtoElp', val: 'Log Ratio Electrical Potential'},
    {key: 'MoM', val: 'Multiple of the median'},
    {key: 'Morph', val: 'Morphology'},
    {key: 'OD', val: 'Optical density'},
    {key: 'Osmol', val: 'Osmolality'},
    {key: 'PctDiff', val: 'Percent difference'},
    {key: 'Prctl', val: 'Percentile'},
    {key: 'Prid', val: 'Presence or Identity'},
    {key: 'PPres', val: 'Pressure (partial)'},
    {key: 'PPresDiff', val: 'Difference in Partial Pressure'},
    {key: 'PPresRto', val: 'Partial Pressure Ratio'},
    {key: 'Pres', val: 'Pressure'},
    {key: 'PresRat', val: 'Pressure Rate'},
    {key: 'PressDiff', val: 'Difference'},
    {key: 'PresRto', val: 'Pressure Ratio'},
    {key: 'Quintile', val: 'Quintile'},
    {key: 'RatDiff', val: 'Rate Difference'},
    {key: 'RelRto', val: 'Relative Ratio'},
    {key: 'Resis', val: 'Resistance'},
    {key: 'ArResis', val: 'Resistance/Area'},
    {key: 'SatFr', val: 'Saturation Fraction'},
    {key: 'Score', val: 'Score'},
    {key: 'ScoreDiff', val: 'Score difference'},
    {key: 'ScoreRange', val: 'Score range'},
    {key: 'Seq', val: 'Nucleotide sequence'},
    {key: 'Susc', val: 'Susceptibility'},
    {key: 'Temp', val: 'Temperature'},
    {key: 'TempDiff', val: 'Temperature difference'},
    {key: 'Tele', val: 'Telephone number'},
    {key: 'Tscore', val: 'T Score'},
    {key: 'TscoreDiff', val: 'T Score difference'},
    {key: 'Txt', val: 'Text'},
    {key: 'ThreshNum', val: 'Threshold Number'},
    {key: 'Titr', val: 'Dilution Factor (Titer)'},
    {key: 'URI', val: 'Uniform Resource Identifier'},
    {key: 'Vel', val: 'Velocity'},
    {key: 'VelRat', val: 'Velocity Rate'},
    {key: 'VelRto', val: 'Velocity Ratio'},
    {key: 'Visc', val: 'Viscosity'},
    {key: 'Zscore', val: 'Z Score'},
    {key: 'Pn', val: 'Person name'},
    //{key: 'Pr', val: 'Presence'},
    {key: 'ID', val: 'Identifier'}
];

exports.time = [
    {key: 'Pt', val: 'Point in time'},
    {key: 'Stdy', val: 'Duration of the study'},
    {key: 'Enctr', val: 'Duration of an encounter'},
    {key: 'Gt', val: 'Greater than'},
    {key: 'Ge', val: 'Greater than or equal to'},
    {key: 'Lt', val: 'Less than'},
    {key: 'Procedure Dur', val: 'Duration of the procedure'},
    {key: 'RptPeriod', val: 'Reporting period'},
    {key: 'XXX', val: 'Not specified'},
    {key: '*', val: 'Life of the “unit”'}
];

exports.system = [
    {key: 'Amnio fld', val: 'Amniotic fluid'},
    {key: 'Asp', val: 'Aspirate'},
    {key: 'Bil fld', val: 'Bile fluid'},
    {key: 'BldA', val: 'Blood arterial'},
    {key: 'BldL', val: 'Blood bag'},
    {key: 'BldC', val: 'Blood capillary'},
    {key: 'BldCo', val: 'Blood – cord'},
    {key: 'BldMV', val: 'Blood- Mixed Venous'},
    {key: 'BldP', val: 'Blood – peripheral'},
    {key: 'BldV', val: 'Blood venous'},
    {key: 'Bld.dot', val: 'Blood filter paper'},
    {key: 'Body fld', val: 'Body fluid, unsp'},
    {key: 'Bronchial', val: 'Bronchial'},
    {key: 'Calculus', val: 'Calculus (=Stone)'},
    {key: 'Cnl', val: 'Cannula'},
    {key: 'CTp', val: 'Catheter tip'},
    {key: 'CSF', val: 'Cerebral spinal fluid'},
    {key: 'Cvm', val: 'Cervical mucus'},
    {key: 'Cvx', val: 'Cervix'},
    {key: 'Col', val: 'Colostrum'},
    {key: 'Cnjt', val: 'Conjunctiva'},
    {key: 'Crn', val: 'Cornea'},
    {key: 'Dentin', val: 'Dentin'},
    {key: 'Dial fld', val: 'Dialysis fluid'},
    {key: 'Dose', val: 'Dose med or substance'},
    {key: 'Duod fld', val: 'Duodenal fluid'},
    {key: 'Endomet', val: 'Endometrium'},
    {key: 'RBC', val: 'Erythrocytes'},
    {key: 'Exhl gas', val: 'Exhaled gas (=breath)'},
    {key: 'Fibroblasts', val: 'Fibroblasts'},
    {key: 'Fistula', val: 'Fistula'},
    {key: 'Food', val: 'Food sample'},
    {key: 'Gast fld', val: 'Gastric fluid/contents'},
    {key: 'Genital', val: 'Genital'},
    {key: 'Genital fld', val: 'Genital fluid'},
    {key: 'Genital loc', val: 'Genital lochia'},
    {key: 'Genital muc', val: 'Genital mucus'},
    {key: 'Inhl gas', val: 'Inhaled gas'},
    {key: 'Isolate', val: 'Isolate'},
    {key: 'WBC', val: 'Leukocytes'},
    {key: 'Line', val: 'Line'},
    {key: 'Liver', val: 'Liver'},
    {key: 'Resp.lower', val: 'Lower respiratory'},
    {key: 'Lung tiss', val: 'Lung tissue'},
    {key: 'Bone mar', val: 'Marrow (bone)'},
    {key: 'Meconium', val: 'Meconium'},
    {key: 'Milk', val: 'Milk'},
    {key: 'Nail', val: 'Nail'},
    {key: 'Nose', val: 'Nose (nasal passage)'},
    {key: 'Nph', val: 'Naspopharynx'},
    {key: 'Penile vessels', val: 'Penile vessels'},
    {key: 'Penis', val: 'Penis'},
    {key: 'Pericard fld', val: 'Pericardial fluid'},
    {key: 'Periton fld', val: 'Peritoneal fluid /ascites'},
    {key: 'Dial fld prt', val: 'Peritoneal dialysis fluid'},
    {key: 'Plas', val: 'Plasma'},
    {key: 'Plr fld', val: 'Pleural fluid (thoracentesis fld)'},
    {key: 'PPP', val: 'Platelet poor plasma'},
    {key: 'PRP', val: 'Platelet rich plasma'},
    {key: 'Pus', val: 'Pus'},
    {key: 'RBCCo', val: 'Red Blood Cells Cord'},
    {key: 'Saliva', val: 'Saliva'},
    {key: 'Semen', val: 'Seminal fluid'},
    {key: 'Ser', val: 'Serum'},
    {key: 'Skin', val: 'Skin'},
    {key: 'Sputum', val: 'Sputum'},
    {key: 'Sptt', val: 'Sputum - tracheal aspirate'},
    {key: 'Stool', val: 'Stool = Fecal'},
    {key: 'Sweat', val: 'Sweat'},
    {key: 'Synv fld', val: 'Synovial fluid (Joint fluid)'},
    {key: 'Tear', val: 'Tears'},
    {key: 'Thrt', val: 'Throat'},
    {key: 'Platelets', val: 'Thrombocyte (platelet)'},
    {key: 'Tiss', val: 'Tissue, unspecified'},
    {key: 'Tlgi', val: 'Tissue large intestine'},
    {key: 'Tsmi', val: 'Tissue small intestine'},
    {key: 'Trachea', val: 'Trachea'},
    {key: 'Tube', val: 'Tube, unspecified'},
    {key: 'Ulc', val: 'Ulcer'},
    {key: 'Urethra', val: 'Urethra'},
    {key: 'Urine', val: 'Urine'},
    {key: 'Urine sed', val: 'Urine sediment'},
    {key: 'Unk sub', val: 'Unknown substance'},
    {key: 'Vag', val: 'Vagina'},
    {key: 'Vitr fld', val: 'Vitreous Fluid'},
    {key: 'Vomitus', val: 'Vomitus'},
    {key: 'Bld', val: 'Whole blood'},
    {key: 'XXX', val: 'Unknown'}
];

exports.method = [
    {val: 'Agglutination', key: 'Aggl'},
    {val: 'Coagulation Assay', key: 'Coag'},
    {val: 'Complement-dependent Cytotoxicity', key: 'CDC'},
    {val: 'Complement Fixation', key: 'Comp fix'},
    {val: 'Cytology Stain', key: 'Cyto stain'},
    {val: 'DNA Nucleic Acid Probe', key: 'Probe'},
    {val: 'Chromogenic/Enzymatic Assay', key: 'Chromo'},
    {val: 'Immunoassay', key: 'EIA'},
    {val: 'Flocculation Assay', key: 'Floc'},
    {val: 'Hemagglutination Inhibition', key: 'HAI'},
    {val: 'Hemagglutination', key: 'HA'},
    {val: 'Immune Blot', key: 'IB'},
    {val: 'Immune Fluorescence', key: 'IF'},
    {val: 'Latex Agglutination', key: 'LA'},
    {val: 'Leukocyte Histamine Release', key: 'LHR'},
    {val: 'Minimum Inhibitory Concentration', key: 'MIC'},
    {val: 'Minimum Lethal Concentration', key: 'MLC'},
    {val: 'Molecular Genetics', key: 'Molgen'},
    {val: 'Neutralization', key: 'Neut'},
    {val: 'Radioimmunoassay', key: 'RIA'},
    {val: 'Rapid Plasma Reagin', key: 'RPR'},
    {val: 'Serum Bacterial Titer', key: 'SBT'},
    {val: 'Rapid Plasma Reagin', key: 'RPR'},
    {val: 'Vertical Auto Profile', key: 'VAP'},
    {val: 'Visual Count', key: 'VC'},
    {val: 'Venereal Disease Research Laboratory', key: 'VDRL'}
];